/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Editor.vue')['default']
    EditorToolbar: typeof import('./src/components/EditorToolbar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PreferencesSheet: typeof import('./src/components/PreferencesSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarDrawer: typeof import('./src/components/SidebarDrawer.vue')['default']
  }
}
